apiVersion: apps/v1
kind: Deployment
metadata:
  name: moodle-deployment
  namespace: moodle
  labels:
    app: moodle
spec:
  replicas: 100
  selector:
    matchLabels:
      app: moodle
  template:
    metadata:
      labels:
        app: moodle
    spec:
      containers:
      - name: moodle
        image: <acr-name>.azurecr.io/moodle:v0.1
        command: ["/init_cron.sh"]
        volumeMounts:
        - mountPath: /var/www/moodledata
          name: moodle-data-volume
        - mountPath: /var/www/localdata
          name: moodle-local-data
        envFrom:
        - secretRef:
            name: moodle-config
        resources:
          limits:
            cpu: 3000m
            memory: 4Gi
          requests:
            cpu: 3000m 
            memory: 4Gi
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      - key: "workload-type"
        operator: "Equal"
        value: "app"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: app
      volumes:
      - name: moodle-data-volume
        nfs:
          server: moodle-data
          path: /data/moodle-data
      - name: moodle-local-data
        emptyDir:
          sizeLimit: 1Gi
          medium: Memory