apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-data
  namespace: moodle
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-csi
  volumeName: moodle-data
  resources:
    requests:
      storage: 100Gi