apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: file.csi.azure.com
  name: moodle-data
  namespace: moodle
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: azurefile-csi
  csi:
    driver: file.csi.azure.com
    volumeHandle: unique-volumeid  # make sure this volumeid is unique for every identical share in the cluster
    volumeAttributes:
      storageAccount: <storage-account-name> # edit with storage account name
      resourceGroup: moodle-high-scale  # optional, only set this when storage account is not in the same resource group as node
      shareName: moodle-data
      server: <storage-account-name>.privatelink.file.core.windows.net # edit with storage account name
      protocol: nfs
    nodeStageSecretRef:
      name: moodle-config
      namespace: moodle