apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer
  namespace: moodle
spec:
  replicas: 4
  selector:
    matchLabels:
      name: pgbouncer
  template:
    metadata:
      labels:
        name: pgbouncer
    spec:
      containers:
      - name: pgbouncer
        image: <acr-name>.azurecr.io/pgbouncer:v0.1 # edit with your acr and image
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pgbouncer-config
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 30
          periodSeconds: 5
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      - key: "workload-type"
        operator: "Equal"
        value: "pgbouncer"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: pgbouncer
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-svc
  namespace: moodle
spec:
  sessionAffinity: ClientIP
  selector:
    name: pgbouncer
  ports:
    - name: pgbouncer-port
      protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-readreplica
  namespace: moodle
spec:
  replicas: 4
  selector:
    matchLabels:
      name: pgbouncer-readreplica
  template:
    metadata:
      labels:
        name: pgbouncer-readreplica
    spec:
      containers:
      - name: pgbouncer-readreplica
        image: <acr-name>.azurecr.io/pgbouncer:v0.1 # edit with your acr and image
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: pgbouncer-config-read-replica
        resources:
          limits:
            cpu: 1000m
            memory: 4Gi
          requests:
            cpu: 1000m
            memory: 4Gi
        livenessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 5432
          initialDelaySeconds: 15
          periodSeconds: 5
        startupProbe:
          tcpSocket:
            port: 5432
          failureThreshold: 30
          periodSeconds: 5
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      - key: "workload-type"
        operator: "Equal"
        value: "pgbouncer"
        effect: "NoSchedule"
      nodeSelector:
        agentpool: pgbouncer
---
apiVersion: v1
kind: Service
metadata:
  name: pgbouncer-read-svc
  namespace: moodle
spec:
  sessionAffinity: ClientIP
  selector:
    name: pgbouncer-readreplica
  ports:
    - name: pgbouncer-readreplica-port
      protocol: TCP
      port: 5432
      targetPort: 5432