apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-cluster
  namespace: moodle
data:
  redis.conf:  |+
    cluster-enabled yes
    cluster-node-timeout 15000
    cluster-config-file /data/nodes.conf
    appendonly yes
    protected-mode no
    dir /data
    port 6379
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-probes
  namespace: moodle
data:
  readiness.sh: |-
    #!/bin/sh

    pingResponse="$(redis-cli -h localhost ping)"
    if [ "$?" -eq "124" ]; then
      echo "PING timed out"
      exit 1
    fi

    if [ "$pingResponse" != "PONG"]; then
      echo "$pingResponse"
      exit 1
    fi
  liveness.sh: |-
    #!/bin/sh

    pingResponse="$(redis-cli -h localhost ping | head -n1 | awk '{print $1;}')"
    if [ "$?" -eq "124" ]; then
      echo "PING timed out"
      exit 1
    fi

    if [ "$pingResponse" != "PONG"] && [ "$pingResponse" != "LOADING" ] && [ "$pingResponse" != "MASTERDOWN" ]; then
      echo "$pingResponse"
      exit 1
    fi