apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-svc
  namespace: moodle
spec:
  clusterIP: None
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    appCluster: redis-cluster
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cache-cluster-svc
  namespace: moodle
spec:
  clusterIP: None
  ports:
  - name: redis-port
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-cache
    appCluster: redis-cache-cluster
  sessionAffinity: None
  type: ClusterIP
