---
- hosts: all
  vars:

  pre_tasks:
    - name: Create the filesystem
      filesystem:
        fstype: ext4
        opts: -L moodle-data
        dev: /dev/disk/azure/scsi1/lun10
      become: true

    - name: Create mount point
      ansible.builtin.file:
        path: /data/moodle-data
        state: directory
        mode: '0755'
      become: true

    - name: Configure mount point
      ansible.posix.mount:
        path: /data/moodle-data
        src: LABEL=moodle-data
        fstype: ext4
        opts: noatime,auto
        state: mounted
      become: true

  roles:
    - role: ansible-nfs-server